name: code analysis & formatting

on: [push]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v2.3.0
      - name: Version
        run: flutter doctor -v
      - name: Install dependencies
        run: flutter pub get
      - name: Linter
        run: flutter analyze
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v2.3.0
      - name: Format
        run: flutter format -n --set-exit-if-changed .
  integration-test:
    # Is recommended to run job with macOS to take advantage of hardware
    # acceleration support provided by HAXM.
    runs-on: macos-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        api-level: [30]
        target: [default, google_apis, playstore]
        arch: [x86_64]
        exclude:
          - target: default
            arch: x86
            api-level: 30
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v2.3.0
      - name: Run integration tests
        uses: nilsreichardt/android-emulator-runner@hot-fix-pre-emulator-launch-script
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          profile: pixel_3a
          emulator-options: -no-snapshot -no-window -no-boot-anim -camera-back virtualscene -camera-front emulated
          working-directory: ./example
          # pre-emulator-launch-script: |
          #   # Insert QR Code image from "integration_test/qr_code.jpg" into the Android
          #   # camera emulator.
          #   # 
          #   # Source: https://stackoverflow.com/a/64922184/8358501
          #   echo "" >> ~/Library/Android/sdk/emulator/resources/Toren1BD.posters
          #   echo "poster qr_code" >> ~/Library/Android/sdk/emulator/resources/Toren1BD.posters
          #   echo "size 2 2" >> ~/Library/Android/sdk/emulator/resources/Toren1BD.posters
          #   echo "position 0 0 -1.8" >> ~/Library/Android/sdk/emulator/resources/Toren1BD.posters
          #   echo "rotation 0 0 0" >> ~/Library/Android/sdk/emulator/resources/Toren1BD.posters
          #   echo "default qr_code.jpg" >> ~/Library/Android/sdk/emulator/resources/Toren1BD.posters
          #   mv integration_test/qr_code.jpg ~/Library/Android/sdk/emulator/resources/
          script: |
            mkdir test_results
            # Download app
            curl -X GET -o "app.apk" "https://firebasestorage.googleapis.com/v0/b/talentscout-34f1b.appspot.com/o/mobile_scanner%2Fapp-release-2.apk?alt=media&token=0ff0a9ad-c691-4ba2-bc9d-f3108455a55f"
            
            # Install app
            adb install app.apk
            # Grant permission
            adb shell pm grant dev.steenbakker.mobile_scanner_example android.permission.CAMERA
            # Open app
            adb shell am start -n dev.steenbakker.mobile_scanner_example/io.flutter.embedding.android.FlutterActivity

            sleep 1
            adb shell screencap -p > test_results/1.jpg
            
            sleep 1
            adb shell screencap -p > test_results/2.jpg
            
            sleep 1
            adb shell screencap -p > test_results/3.jpg
            
            sleep 1
            adb shell screencap -p > test_results/4.jpg
            
            sleep 1
            adb shell screencap -p > test_results/5.jpg

            sleep 1
            adb shell screencap -p > test_results/6.jpg
      - name: Upload emulator tests artifact
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: failure_screenshots_${{ matrix.target }}_${{ matrix.arch }}_${{ matrix.api-level }}
          path: ./example/test_results
      